### ISSUE TITLE
Add a Version header to API requests

### ISSUE THREAD

**Issue by AdamVig** [stockpile-co/app#339]
As the API developer,
I want to know what version of the app is making each request
so that I can provide different responses based on the version.

**Comment by emroussel** [comment]
It actually seems to be more common to request a specific api version from the app instead of letting the api decide what version to use depending on the app version.

There seems to be three ways of doing this:
- Add the version in the URL (i.e. `https://stockpileapp.co/api/v2`)
- Add the version in a custom request header (i.e. `Api-Version: 1.0.0`)
- Add the version in the Accept header (i.e. `Accept: application/vnd.stockpile.api.v2+json`)

I'm not a fan of the url method, but don't have a strong preference toward the custom or Accept header.

We could also do it as originally proposed and have the app send the app version to the api and let the api decide what version to use.

I think the pros and cons are:
**Have app request api version**
Pros:
- Better separation of concerns (api does not have to know what is consuming it)

Cons:
- Risk to forget to update api version on the app and have things break

**Have app send app version**
Pros:
- Code on the app would be automated, so no risk to forget to update version
- Greater flexibility right now (easier to fix things and make the app use a new api after app is released)

Cons:
- Will have to use a native plugin to get the app version, so it might make running the app in the browser more complicated (cordova not available, so will have to mock it somehow)
- Lesser flexibility in the future (if we somehow have a different app consuming the api or make it public, api versioning would easily break since apps with different versions would use it)

I think I am leaning more toward having the app request a specific api version, but a lot of people complain online about how the current way of doing api versioning is broken, so I am totally open to using an unconventional solution if it seems better in our situation.

@AdamVig what are your thoughts?

**Comment by AdamVig** [comment]
Thanks for such a good writeup of our options!

Look at [Restify's support for versioned routes](http://restify.com/docs/home/#versioned-routes). The framework has baked-in support for an `Accept-Version` header with a semver string, which could cover version spans like `~3` for any version of the endpoint starting with `3`, like `3.0.0`, `3.5.13`, etc.

Using this would fall under the "have app request API version" option, but it would be on a per-endpoint basis, so it would be more granular than API-wide versioning.

We would hard-code a major version for each endpoint into the app, then when a breaking change is made on an endpoint, we would increment that endpoint to the next major version, and the app would still make requests to the old version of that endpoint.

Let's add an `Accept-Version` header to requests for each endpoint. In tandem with that, I'll have to specify a version for each endpoint, too, so we'll need to release these changes at the same time.

**Comment by emroussel** [comment]
Ok sounds good!
